project:
  type: website
  output-dir: docs

website:
  title: "Jiachen Xu"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: hw2/hw2_questions.qmd
        text: HW2


format:
  html:
    theme: minty
    css: styles.css
    toc: true